// <auto-generated />
namespace CodeFirstUsingDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_courses_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_courses_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202304160626059_added_courses_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
